# Generated by Django 6.0.1 on 2026-01-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_booking_quantity_booking_additional_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='is_restored',
            field=models.BooleanField(default=False),
        ),
    ]
