# Generated by Django 6.0.1 on 2026-03-19 17:12

from django.db import migrations

def migrate_data(apps, schema_editor):
    Order = apps.get_model('api', 'Order')
    # Mark old paid or delivered orders as confirmed
    Order.objects.filter(is_paid=True).update(is_confirmed=True)
    Order.objects.filter(is_delivered=True).update(is_confirmed=True)
    
    # Ensure default payment method is set for old orders
    Order.objects.filter(payment_method='').update(payment_method='M-Pesa')

def reverse_migrate_data(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_is_confirmed_order_is_failed_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_data, reverse_migrate_data),
    ]
