# Generated by Django 6.0.1 on 2026-02-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_goods_stock_quantity_order_is_restored'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_out_for_service',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_pending',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
