# Generated by Django 5.0.3 on 2026-05-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='car_models',
            field=models.CharField(blank=True, help_text='Comma separated list of car models', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='service_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
