# Generated by Django 5.0.3 on 2026-05-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_productimage_car_models_productimage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceimage',
            name='image_type',
            field=models.CharField(choices=[('before', 'Before'), ('after', 'After'), ('general', 'General')], default='general', max_length=10),
        ),
    ]
